# Generated by Django 4.0.1 on 2022-02-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_total',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
