# Generated by Django 4.0.1 on 2022-06-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_like_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to='login.user')),
            ],
        ),
    ]
