# Generated by Django 4.0.1 on 2022-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='Q1',
            field=models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, verbose_name='问题1'),
        ),
        migrations.AddField(
            model_name='test1',
            name='Q2',
            field=models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, verbose_name='问题2'),
        ),
        migrations.AddField(
            model_name='test1',
            name='Q3',
            field=models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, verbose_name='问题1'),
        ),
    ]
