# Generated by Django 4.0.1 on 2022-07-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_user_like_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usermodel',
        ),
    ]
