# Generated by Django 4.0.1 on 2022-07-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_user_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usermodel',
            new_name='User',
        ),
    ]
