# Generated by Django 4.0.1 on 2022-07-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_status_user_match_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_receive', models.SmallIntegerField(default=1, verbose_name='收到喜欢')),
                ('user_deliver', models.SmallIntegerField(default=1, verbose_name='提出喜欢')),
            ],
        ),
    ]
